name: Gururi
fileGroups:
  - configs
configFiles:
  Debug: configs/Debug.xcconfig
  Release: configs/Release.xcconfig
targets:
  Gururi:
    type: application
    platform: iOS
    sources: Gururi
    configFiles:
      Debug: configs/Gururi-Debug.xcconfig
      Release: configs/Gururi-Release.xcconfig
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: com.rndv.Gururi
      CURRENT_PROJECT_VERSION: 1
      DEVELOPMENT_TEAM: T8LL8NK3R5
